#####
# Database
#####
database:
  url: "jdbc:mysql://host:port/openmc"
  username: ""
  password: ""

features:
  analytics: true
  transactions: true
  aywen_pelush:
    day: 3
    month: 11
    year: 2025

chat:
  # {prefix}, {suffix}, {name}, {message}
  message: "&r{prefix} {name}&8: &f{message}"

# Montant d'argent donné à un joueur lors de sa première connexion
money-on-first-join: 500

#####
# Paramètres pour un environnement de production
#####
homepage: "https://openmc.fr/"
discord: "https://aywen.fr/discord/"
blog: "https://blog.openmc.fr/"
wiki: "https://wiki.openmc.fr/"
repoV2: "https://github.com/ServerOpenMC/PluginV2"

#####
# Webhook
#####
error:
  notif: [ ]
  webhook: "https://discord.com/api/webhooks/..."